experiment_params:
  levels: 4
  passability: 7200
  train_tests: 10
  validation_tests: 5
  agent_type: BASE
  episodes: 10
  experiment_name: null
elevators:
  1:
    elevator_weight: 680
  2:
    elevator_weight: 680
