data_params:
  levels: 10
  passability: 1000
  days: 7
  train_tests: 10
  validation_tests: 5
case_params:
  elevators: 2
  agent_type: DQL
  elevator_weight: [680, 1040]
  episodes: 10
  case_name: null