case_params:
  elevators: 1
  levels: 4
  passability: 720
  train_tests: 12
  validation_tests: 1
experiment_params:
  agent_type: DQL
  elevator_weight: 680
  episodes: 100
  experiment_name: qeQp6bg
