case_params:
  elevators: 1
  levels: 4
  passability: 7200
  train_tests: 50
  validation_tests: 5
experiment_params:
  agent_type: DQL
  elevator_weight: 680
  episodes: 50
  experiment_name: RkkIhYG