from enum import Enum


class RewardType(Enum):
    WAIT_WHEN_NO_CALLS = 100
    CLOSE_DOOR = 0
    GET_PASSENGER = 250
    DELIVER_PASSENGER = 250

    PASSENGER_WAIT = 5
    WAIT_WHEN_CALLS = 0
    OPEN_ON_EMPTY_LEVEL = 0
    MOVE_NEXT_TO_EDGE = 1000
    MOVE_WITH_OPEN_DOOR = 1000
