from enum import Enum


class RewardType(Enum):
    WAIT_WHEN_NO_CALLS = 10
    CLOSE_DOOR = 15
    GET_PASSENGER = 150
    DELIVER_PASSENGER = 250

    MOVE_BETWEEN_LEVELS = 5
    OPEN_CLOSE_DOOR = 10
    PASSENGER_WAIT = 2
    WAIT_WHEN_CALLS = 50
    OPEN_ON_EMPTY_LEVEL = 50
    MOVE_NEXT_TO_EDGE = 1000
    MOVE_WITH_OPEN_DOOR = 1000
